GET http://localhost:4000/

###

POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "email": "ahmet@sistemgaraj.com",
  "password": "Ahmet6167@",
  "username": "Ahmet"
}

###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "ahmet@sistemgaraj.com",
  "password": "sifre123"
}

###

@token = BURAYA_LOGIN_DAN_ALDIĞIN_TOKEN_GELECEK

POST http://localhost:4000/api/builds
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "İlk Oyun Bilgisayarım",
  "cpuId": "BURAYA_CPU_ID",
  "motherboardId": "BURAYA_ANAKART_ID",
  "ramId": "BURAYA_RAM_ID",
  "gpuId": "BURAYA_GPU_ID",
  "psuId": "BURAYA_PSU_ID",
  "caseId": "BURAYA_KASA_ID",
  "isPublic": true
}

###

GET http://localhost:4000/api/builds

###

@buildId = BURAYA_BUILD_ID

POST http://localhost:4000/api/builds/{{buildId}}/like
Authorization: Bearer {{token}}

###

POST http://localhost:4000/api/builds/{{buildId}}/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "Efsane bir sistem olmuş, tebrikler!"
}

###

GET http://localhost:4000/api/builds/{{buildId}}

###

GET http://localhost:4000/api/users/ahmet